apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-example
  labels:
    app: rest-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-example
  template:
    metadata:
      labels:
        app: rest-example
        tier: backend
    spec:
      containers:
        - name: rest-example
          image: prasaduvce/rest-example
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi

